# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03c9e8a6a335b6e393f28f695695b3a84b42f5172fdbcd73e84d7b929036e63261dd7f37d378b4df39b8e8a56534157a6078eff59c96cdf0946f4dc9af737763

test:
  secret_key_base: 4ff7924968f8462e52783341ecc81f49724fc08ee73da70bd2d65876a6ba5d927a2ca731f6ff58e94de1007c6172fe578f041a6d95120a1cc8c094c8c4d53dbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
